version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web:/var/www/html"
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always
    depends_on:
      - php
      - mysql
  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./web:/var/www/html"
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOSTNAME}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ONETIME_PASSWORD=${MYSQL_ONETIME_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
